### ISSUE TITLE
recipe[nginx::source] headers_more_module compile error.

### ISSUE THREAD

**Issue by ogis-nakagawa** [miketheman/nginx#316]
Hi, I want to build nginx from source with the headers_more_module. 
```yaml
  "nginx": {
    "version": "1.4.4"
    "repo_source": "nginx",
    "default_site_enabled": false,
    "install_method": "source",
    "source": {
      "modules": [
        "nginx::headers_more__module"
      ]
    }
  }
```
But, build fails.
Cause of failure is a tarball been changed to "openresty-headers-more-nginx-module-*".

Please, modify recipe of nginx::headers-more-module.rb.
```
bash 'extract_headers_more' do
  cwd  ::File.dirname(tar_location)
  user 'root'
  code <<-EOH
    tar -zxf #{tar_location} -C #{module_location}
    mv -f #{module_location}/*/* #{module_location}
  EOH
  not_if { ::File.exists?("#{module_location}/config") }
end
```
