### ISSUE TITLE
Nginx::Source running every time

### ISSUE THREAD

**Issue by mmahalwy** [miketheman/nginx#322]
Is there a way to avoid this and not using the default? I have other cookbooks that require ::source but are now triggering everytime.

**Comment by rmoriz** [comment]
Can't reproduce with Ubuntu 12.04 and .kitchen.yml:

```yaml
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
        - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[nginx::source]
```

Issue invalid?
